### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by gunicsba** [GNSSOEM/ELT_RTKBase_old#1]
If this is based on https://github.com/Stefal/rtkbase then I'd expect the following:

- Give credit to him
- Keep the original license (it doesn't allow relicensing)
- Publish the source code not just the final product (preferably have these changes reach back the original software)

Thank you

**Comment by Jef239** [comment]
1) This is a file hosting based on https://github.com/GNSSOEM/UM980_RPI_Hat_RtkBase
It was created to distribute a huge file with an image. Therefore, it is recreated anew with the release of each new version. Literally in an hour I will delete it and create it again.

2) Please move your comments to https://github.com/GNSSOEM/UM980_RPI_Hat_RtkBase Here they will simply disappear.

3) I communicate with @Stefal, he has no complaints. You can read in https://github.com/Stefal/rtkbase/issues/351 for example.

4) About licenses... You are partially right.

" Notwithstanding any other provision of this License, you have
permission to link or combine any covered work with a work licensed
under version 3 of the GNU General Public License into a single
combined work, and to convey the resulting work. The terms of this
License will continue to apply to the part which is the covered work,
but the work with which it is combined will remain governed by version
3 of the GNU General Public License."
Source - https://github.com/Stefal/rtkbase?tab=AGPL-3.0-1-ov-file

Since most of what is included in this repository (actually 99.99% - this is Debian 12) is under GPL 3.0, the entire repository must be under GPL.

5) But in https://github.com/GNSSOEM/UM980_RPI_Hat_RtkBase the license is indeed mixed up. And it looks like this will have to be fixed. But not right away, but when I study the issue in more detail.

**Comment by Jef239** [comment]
I think that the right answer to the crazy demands of copyright zealots is to stop free distribution of the Debian image and leave it only for a fee.

Anyone who needs our Debian image can easily buy it at the extremely favorable price of 300 euros excluding taxes together with the entire device, remove the SD card from the device and copy the image from there.

In this case, I will not have to print a list of tens of thousands of names of those who contributed to the Linux Kernel and Debian much more than stefal.

I remind you that the GPL does not require me to freely distribute the Debian image. In exactly the same way, it does not require sticking a license on the SD card.

So the ELT_RTKBase repository will be removed in the coming days, and another repository will be moved in its place (so that the name does not disappear).

I hope that everyone who can't work with SSH and create a Debian image on their own will thank you very much for stopping free access to it.

I'll wait a couple of days, of course. But for now I don't see any other way to satisfy your crazy demands.

**Comment by Jef239** [comment]
The GNSSOEM/ELT_RTKBase repository has been removed, you can rejoice about it.

Its name will be taken by another repository.
